name: Build and upload binary artifact

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    name: Build, package and upload .jar artifact
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: 'adopt'
    - name: Build and package project
      run: mvn -f pom.xml package
    - name: Upload Maven build artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: ./target/spring-github-actions-demo-0.1.jar
