name: Deploy to App services

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to azure App services
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure Web App Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'applicationthroughgitaction'
          slot-name: 'development'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./target/*.jar
